### ISSUE TITLE
[Refactor] Use Action Creator for the actions

### ISSUE THREAD

**Issue by Knochenmark** [Knochenmark/recipebox#13]

**Comment by brass-eye** [comment]
Aren't action creators already being used? I thought the functions starting at line 68 in `src/actions/RecipeActions.ts` were action creators?

**Comment by Knochenmark** [comment]
@brass-eye Hi, yes there are action creators, but I wasn't that happy with how the payload isn't typesafe. I was thinking about trying out the ActionCreator from redux. If you have other recommendations, i am open for suggestions, since I am rather new to React.

**Comment by artfuldev** [comment]
Planning to work on this.

**Comment by Knochenmark** [comment]
@artfuldev Go ahead.
