### ISSUE TITLE
Hide searchField reset when value is empty

### ISSUE THREAD

**Issue by Knochenmark** [Knochenmark/recipebox#56]
The search field in the index and Bookmark view to search for recipes has a cross to reset its value. The cross should be hidden until there was an value entered in the field. When the value ist just an empty string, the reset icon isnt required yet and therefore shouldnt be displayed.

**Comment by KumarManoj-S** [comment]
Hi, can I take this up?

**Comment by Knochenmark** [comment]
@KumarManoj-S Sure, i guess you only need a conditional for the icon.

**Comment by KumarManoj-S** [comment]
Yes @Knochenmark. I have made the changes and raised the pull request.
Looking forward to solve more issues.

**Comment by Knochenmark** [comment]
@KumarManoj-S Thanks, I already merged the changes.
